FROM alpine:3.20
WORKDIR /opt/alist/
ADD https://github.com/AlistGo/alist/releases/latest/download/alist-linux-musl-amd64.tar.gz /tmp/alist.tar.gz
RUN tar -xzf /tmp/alist.tar.gz -C /opt/alist/ && \
    chmod +x /opt/alist/alist && \
    rm -f /tmp/alist.tar.gz
EXPOSE 5244
CMD ["/opt/alist/alist", "server", "--no-prefix"]
