FROM golang:1.23-alpine3.19 AS builder
RUN apk add --no-cache bash git musl-dev gcc
WORKDIR /app/
COPY go.mod go.sum ./
RUN go mod download || true
COPY . ./
RUN go get github.com/glebarez/sqlite@latest && \
    go mod tidy && \
    CGO_ENABLED=0 go build \
    -buildmode=pie \
    -tags=jsoniter \
    -trimpath \
    -ldflags "-s -w -linkmode external -extldflags=-static" \
    -o /alist .

FROM alpine:3.19
WORKDIR /opt/alist/
COPY --from=builder /alist /opt/alist/alist
EXPOSE 5244
ENTRYPOINT ["/opt/alist/alist", "server", "--no-prefix"]
